add custom middlewares option
go-pkgz/jrpc pull request #11
Opened 2021-11-18 20:38 UTC by zebox

In this PR implemented custom middlewares option as mention #8. The options `CustomMiddlewares`  added direct to `Server` struct with type  `Middlewares` which was define too.

2021-11-18 20:50 UTC, umputun requested changes
thx, a small suggestion. In addition readme wording is somewhat confusing but I'll rephrase it after the merge

2021-11-18 20:50 UTC, umputun commented on server.go
> -	router.Use(middleware.Throttle(s.Limits.ServerThrottle), middleware.RealIP, rest.Recoverer(s.Logger))
I think we should keep throttler, realio and recoverer in the default set of middlewares. If throttle is smth not tha obvious but both realip and recoverer are must have

2021-11-18 23:11 UTC, umputun commented on server.go
> -	router.Use(middleware.Throttle(s.Limits.ServerThrottle), middleware.RealIP, rest.Recoverer(s.Logger))
i know the original ticket mentioned realip and recoverer as something user may pass, but I can't see any use case where user may want to skip these two. Well, maybe realip (not sure why, but anyway) but lack of recoverer will fail server on errors

2021-11-20 03:17 UTC, zebox commented
If are you don't have remarks could you LGTM?

2021-11-20 19:10 UTC, umputun commented
I don't see any problem with your PR on the code level. My only concern is "silently braking" nature of this change. I.e. consumer gets this version and the behavior changes behind the scene. This could be something unexpected and even potentially dangerous.  I would rather prefer a breaking change of some sort, very explicit one instead of the current implicit change of the logic.

I'm not sure what the best/right solution here. We can accept the risk, we can make not-compatible change, or we can make the old configuration default and allow "undefault" it somehow, or maybe something else.

2021-11-20 19:42 UTC, zebox commented
I understand you fear and you are righ. May be stay all previous middlewares by default as you offer and mark they as deprecated for future release?

I need add custom middlewares only  and use main stream of you package. If you think solution which I offer dangerous I will use fork for my case.

2021-11-20 20:01 UTC, umputun commented
I think the best we can do here is to break the current API intentionally. This is what I'd suggest:

- make Server constructible with NewServer and change all the fields to private
- the constructor will get a single parameter `API`
- everything else, including the custom list of middlewares passed in with optional func pattern, like [here](https://github.com/go-pkgz/lgr/blob/master/options.go)

This way we make the change breaking, so no confusions on silently changed functionality. Also, dealing with default/non-default will be much easier, for example one of options will be `WithLogger` and by default it will set nop logger. The same logic will be about all the other parts, i.e. WithThrottler, WithLimits and so on. Obviously custom middlewares will have `WithMiddlewares` option

what do you think?

2021-11-21 05:19 UTC, zebox commented
I think it's good idea. But I'm thinking close this PR, because discussed changes not relevant with it.

I will add change with new options for server configure and will open new PR.

2021-11-21 16:16 UTC, closed without merging